Repository ArtiomTr/jest-coverage-report-action, pull requests merged in 2021-09, with the labels that each got.

#156 Used coverage and base coverage file options
  src/format/strings.json
  src/run.ts
  src/stages/collectCoverage.ts
  src/stages/getCoverage.ts
  src/typings/Report.ts
  tests/stages/collectCoverage.test.ts
  tests/stages/getCoverage.test.ts
Labels: bug

#157 Excluded index.ts file from coverage collection
  jest.config.js
Labels: enhancement

#158 Updated jest
  package-lock.json
  package.json
Labels: dependencies

#155 update docs: describe how to change annotations
  README.md
Labels: documentation

#160 Added possiblity to not specify format-specific arguments in test script
  action.yml
  src/stages/runTest.ts
  src/utils/getTestCommand.ts
  src/utils/isOldScript.ts
  tests/stages/getCoverage.test.ts
  tests/stages/runTest.test.ts
  tests/utils/getTestCommand.test.ts
  tests/utils/isOldScript.test.ts
Labels: enhancement

#163 Refactored errors
  src/format/formatErrors.ts
  src/format/strings.json
  src/stages/collectCoverage.ts
  src/stages/getCoverage.ts
  src/stages/parseCoverage.ts
  src/typings/ActionError.ts
  src/utils/DataCollector.ts
  tests/format/__snapshots__/formatErrors.test.ts.snap
  tests/format/formatErrors.test.ts
  tests/run.test.ts
  tests/stages/collectCoverage.test.ts
  tests/stages/getCoverage.test.ts
  tests/stages/parseCoverage.test.ts
  tests/utils/DataCollector.test.ts
Labels: enhancement

#165 `npx` and `pnpx` are not npm style
  src/utils/getTestCommand.ts
Labels: bug

#169 Set up security policy
  SECURITY.md
Labels: documentation

#170 Update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/documentation.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation
