Repository ArtiomTr/jest-coverage-report-action, pull requests merged in 2021-12, with the labels that each got.

#201 Fix action name and version on README
  README.md
Labels: documentation

#204 remove if option from minimal configuration on README
  README.md
Labels: documentation

#210 Use jest config instead of threshold option
  dist/index.js
  package-lock.json
  package.json
  src/format/details/parseDetails.ts
  src/format/formatThresholdResults.ts
  src/format/strings.json
  src/run.ts
  src/stages/checkThreshold.ts
  src/stages/collectCoverage.ts
  src/stages/createReport.ts
  src/typings/JestThreshold.ts
  src/typings/Report.ts
  src/typings/ThresholdResult.ts
  src/utils/accumulateCoverageDetails.ts
  src/utils/checkSingleThreshold.ts
  src/utils/getCoverageForDirectory.ts
  src/utils/getFileCoverageMap.ts
  src/utils/getNormalThreshold.ts
  src/utils/parseJestConfig.ts
  src/utils/tryGetJestThreshold.ts
  tests/stages/__snapshots__/createReport.test.ts.snap
  tests/stages/collectCoverage.test.ts
  tests/stages/createReport.test.ts
  tests/stages/getCoverage.test.ts
Labels: enhancement

#212 Dropped rmdir usage for node versions >= 14.14.0
  __mocks__/fs-extra/index.ts
  package-lock.json
  package.json
  src/stages/checkThreshold.ts
  src/stages/installDependencies.ts
  src/utils/__mocks__/removeDirectory.ts
  src/utils/removeDirectory.ts
  tests/stages/getCoverage.test.ts
  tests/stages/installDependencies.test.ts
  tests/utils/isOldScript.test.ts
  tests/utils/removeDirectory.test.ts
Labels: bug

#213 docs: fix mini typo
  README.md
Labels: documentation
