Repository ArtiomTr/jest-coverage-report-action, pull requests merged in 2021-06, with the labels that each got.

#42 Added possibility to choose icons
  action.yml
  dist/index.js
  src/format/Icons.ts
  src/format/details/formatCoverageDetails.ts
  src/format/details/formatCoverageDetailsPart.ts
  src/format/details/getFileCoverageDetailRow.ts
  src/format/getFormattedCoverage.ts
  src/format/getFormattedFailReason.ts
  src/format/strings.json
  src/format/summary/formatCoverageSummary.ts
  src/format/utils/formatPercentage.ts
  src/format/utils/formatPercentageDelta.ts
  src/format/utils/getStatusOfPercents.ts
  src/index.ts
  src/report/generateReport.ts
Labels: enhancement

#44 Created failed tests annotations
  action.yml
  dist/index.js
  package-lock.json
  package.json
  src/annotations/createFailedTestsAnnotations.ts
  src/annotations/isAnnotationEnabled.ts
  src/annotations/isAnnotationsOptionValid.ts
  src/collect/collectCoverage.ts
  src/collect/getRawCoverage.ts
  src/collect/parseCoverage.ts
  src/collect/parseJsonReport.ts
  src/format/annotations/formatFailedTestsAnnotations.ts
  src/format/annotations/getFailedAnnotationsSummary.ts
  src/format/annotations/getFailedTestsAnnotationsBody.ts
  src/format/strings.json
  src/index.ts
  tests/parseCoverage.test.ts
Labels: enhancement

#52 Fixed testing action
  .github/workflows/test.yml
Labels: bug

#55 Fixed problems with variables injection
  dist/index.js
  src/format/details/formatCoverageDetails.ts
  src/report/generateReport.ts
Labels: bug

#66 Fixed documentation dependencies
  docs/package-lock.json
  docs/package.json
Labels: bug, dependencies, documentation

#67 Fixed documentation dependencies
  .github/workflows/docs-deploy.yml
  docs/package-lock.json
  docs/package.json
Labels: bug, dependencies, documentation

#68 Fixed screenshot in documentation
  docs/assets/coverage-comment-example.jpg
Labels: bug, documentation

#69 Added possibility to create markdown pages
  docs/mdx.d.ts
  docs/next.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/components/EditorWithCopy.tsx
  docs/src/components/Header.tsx
  docs/src/components/layouts/LayoutDocs.tsx
  docs/src/components/layouts/LayoutProps.ts
  docs/src/components/markdown/Code.module.scss
  docs/src/components/markdown/Code.tsx
  docs/src/components/markdown/MarkdownHeading.module.scss
  docs/src/components/markdown/MarkdownHeading.tsx
  docs/src/components/markdown/MarkdownWrapper.tsx
  docs/src/components/markdown/components.tsx
  docs/src/pages/_document.tsx
  docs/src/pages/index.tsx
  docs/src/theme.ts
  docs/tools/.eslintrc
  docs/tools/loaders/md-loader.js
  docs/tools/scripts/deploy.js
  docs/tsconfig.json
Labels: documentation

#70 Create quick start guide
  docs/src/components/EditorWithCopy.tsx
  docs/src/components/Header.module.scss
  docs/src/components/Header.tsx
  docs/src/components/Rating.tsx
  docs/src/components/layouts/LayoutDocs.tsx
  docs/src/components/markdown/Code.module.scss
  docs/src/components/markdown/Code.tsx
  docs/src/components/markdown/MarkdownHeading.module.scss
  docs/src/components/markdown/MdLink.tsx
  docs/src/components/markdown/components.tsx
  docs/src/pages/index.tsx
  docs/src/pages/quick-start.md
Labels: documentation

#72 Allow to skip deps installation and/or running the test script
  .github/workflows/test.yml
  README.md
  action.yml
  dist/index.js
  docs/src/pages/quick-start.md
  package-lock.json
  src/collect/collectCoverage.ts
  src/collect/getRawCoverage.ts
  src/index.ts
  src/typings/Options.ts
Labels: bug, documentation, enhancement

#73 Add `package-manager`option
  .github/workflows/docs-deploy.yml
  README.md
  action.yml
  dist/index.js
  docs/src/pages/index.tsx
  src/collect/collectCoverage.ts
  src/collect/getRawCoverage.ts
  src/index.ts
  src/typings/Options.ts
Labels: enhancement

#79 Created migration guide
  docs/src/components/Header.tsx
  docs/src/components/markdown/Code.tsx
  docs/src/pages/_app.tsx
  docs/src/pages/migrate.md
  docs/src/pages/quick-start.md
Labels: documentation

#80 Set up footer links
  docs/src/components/Footer.tsx
  docs/src/components/FooterLink.tsx
  docs/src/components/FooterSection.tsx
  docs/src/components/Header.tsx
  docs/src/components/LinkProps.ts
  docs/src/pages/_app.tsx
Labels: documentation

#81 Small documentation style fixes
  docs/src/components/Header.tsx
  docs/src/components/landing/InfoScreen.tsx
  docs/src/pages/_app.tsx
  docs/src/pages/index.tsx
  docs/styles/globals.css
Labels: documentation

#83 Configured image optimization for documentation
  docs/next-env.d.ts
  docs/next.config.js
  docs/package-lock.json
  docs/package.json
  docs/src/components/ResponsiveImage.tsx
  docs/src/components/landing/InfoImageScreen.tsx
  docs/src/pages/_app.tsx
  docs/src/pages/index.tsx
Labels: documentation

#84 Created documentation for configuration
  .vscode/settings.json
  action.yml
  docs/assets/coverage-annotation-example.jpg
  docs/assets/failed-test-annotation-example.jpg
  docs/mdx.d.ts
  docs/src/components/Header.tsx
  docs/src/components/markdown/MarkdownHeading.tsx
  docs/src/components/markdown/components.tsx
  docs/src/pages/configuration.md
  docs/tsconfig.json
Labels: documentation

#87 Fixed example in readme
  README.md
Labels: documentation

#89 Created robots.txt file
  docs/public/robots.txt
Labels: documentation

#90 Set up google analytics for documentation
  docs/public/analytics.js
  docs/src/pages/_document.tsx
Labels: documentation

#93 Removed CI_JOB_NUMBER from readme file
  README.md
  docs/src/pages/index.tsx
Labels: documentation

#99 Created possibility to run on push
  dist/index.js
  src/index.ts
  src/report/generateCommitReport.ts
  src/report/generatePRReport.ts
  src/report/generateReport.ts
  src/report/getReportBody.ts
Labels: enhancement

#103 doc: add support `[skip ci]`
  README.md
Labels: documentation
