Repository ArtiomTr/jest-coverage-report-action, pull requests merged in 2022-09, with the labels that each got.

#312 Implement `output` option
  README.md
  action.yml
  dist/index.js
  dist/index.js.map
  package-lock.json
  package.json
  src/format/annotations/CreateCheckOptions.ts
  src/format/strings.json
  src/report/generateCommitReport.ts
  src/report/generatePRReport.ts
  src/run.ts
  src/typings/Options.ts
  src/utils/getPrPatch.ts
  tests/format/annotations/formatCoverageAnnotations.test.ts
  tests/format/annotations/formatFailedTestsAnnotations.test.ts
  tests/report/fetchPreviousReport.test.ts
  tests/report/generateCommitReport.test.ts
  tests/report/generatePRReport.test.ts
  tests/run.test.ts
  tests/stages/createReport.test.ts
  tests/stages/getCoverage.test.ts
  tests/typings/Options.test.ts
Labels: enhancement

#315 Fix quick start link from home page
  docs/src/pages/index.tsx
Labels: documentation

#316 Set approximation threshold to 0
  src/utils/formatPercentage.ts
Labels: bug
